### ISSUE TITLE
Error! request_path request_path is an unknown field

### ISSUE THREAD

**Issue by javeme** [ajaysreedhar/kongdash#13]
When doing "Add new API", the following error occurred:
Error! request_path request_path is an unknown field.

Gateway Version: 0.10.0rc3

**Comment by gradano-c4w** [comment]
I think because of
https://github.com/Mashape/kong/pull/1970

**Comment by ajaysreedhar** [comment]
[New version](https://github.com/ajaysreedhar/kongdash/releases/tag/v0.3.0) compatible with gateway version 0.10.x is available now.
