### ISSUE TITLE
Any plan vor 0.10.x

### ISSUE THREAD

**Issue by se** [ajaysreedhar/kongdash#14]
Hi guys!

Any plan for 0.10 ?

**Comment by inluxc** [comment]
I starting to make changes to it in my repo then i will make a pull request over here if the project still alive.

**Comment by ajaysreedhar** [comment]
@se sure. but unfortunately I didn't have enough time to work on it further.

**Comment by ajaysreedhar** [comment]
@inluxc please go ahead.

**Comment by ajaysreedhar** [comment]
[New version](https://github.com/ajaysreedhar/kongdash/releases/tag/v0.3.0) with support for 0.10.x available now.
