### ISSUE TITLE
manage upstreams

### ISSUE THREAD

**Issue by dirham** [ajaysreedhar/kongdash#16]
based on [this](https://getkong.org/docs/0.10.x/loadbalancing/) It would be nice if we can manage upstreams.

**Comment by ajaysreedhar** [comment]
Working on it. API 0.10.x compatible version will be released soon.

**Comment by ajaysreedhar** [comment]
Available in [v0.3.0](https://github.com/ajaysreedhar/kongdash/releases/tag/v0.3.0)
