### ISSUE TITLE
Changing host in Settings does not refresh dashboard

### ISSUE THREAD

**Issue by wshirey** [ajaysreedhar/kongdash#2]
Great work and thanks for sharing your dashboard! 

I did find a bug where the dashboard isn't reloading data when the host URL is changed, i.e., data from previous host is persisted in application state. Only restarting the application remedies this.

**Comment by wshirey** [comment]
Looks like maybe the configuration is cached in the ajax provider.

**Comment by ajaysreedhar** [comment]
Fixed in [v0.3.0](https://github.com/ajaysreedhar/kongdash/releases/tag/v0.3.0)
