### ISSUE TITLE
Great UI and Easy to Use

### ISSUE THREAD

**Issue by keithkk** [ajaysreedhar/kongdash#9]
I installed the Windows x64 version and have it up and running now. At first glance, great job on a very nice UI. I'm very happy to have come across your site. I'd be happy to continue testing away and provide feedback on things I run into. If there are other ways I could help contribute, let me know. Thanks!

**Comment by ajaysreedhar** [comment]
Glad to know that you liked it. But unfortunately i haven't had enough time to work on it further. All kinds of contributions are always welcome.
